name: Build, Lint & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-macos:
    name: Build & Test (macOS)
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build package
      run: make build
    - name: Run tests
      run: make test-with-coverage
    - name: Generate Code Coverage
      run: |
        xcrun llvm-cov export \
          .build/debug/FlowPackageTests.xctest/Contents/MacOS/FlowPackageTests \
          -instr-profile .build/debug/codecov/default.profdata \
          --format="lcov" \
          --ignore-filename-regex "\\.build" \
          --ignore-filename-regex "Tests" > info.lcov
    - name: Upload Code Coverage
      run: |  
        bash <(curl -s https://codecov.io/bash) \
          -J 'Flow' \
          -G info.lcov

  build-test-linux:
    name: Build & Test (Linux)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build package
      run: make build
    - name: Run tests
      run: make test

  lint:
    name: Lint
    runs-on: macos-15
    steps:
    - uses: actions/checkout@v4
    - name: Install SwiftLint
      run: |
        brew install swiftlint
        swiftlint --version
    - name: Lint
      run: make lint